/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package gradle.constants.test;

import org.junit.jupiter.api.Test;

import static gradle.constants.test.Library.CONSTANT;

class LibraryTest {

    public static final String TEST_CONSTANT = "Hello from LibraryTest";
    @Test
    void someLibraryMethodReturnsTrue() {
        System.out.println(CONSTANT);
        System.out.println(LibraryTest.TEST_CONSTANT);
    }
}
